/*

VANTAGENS E DESVANTAGENS S.O.L.I.D

VANTAGENS:

- CODIGO MODULAR
- CODIGO REUTILIZAVEL (DRY - Don't Repeat Yourself)
- CÓDIGO TESTAVEL, BAIXO ACOPLAMENTO
- BAIXO ACOPLAMENTO E ALTA COESÃO
- FACILIDADE DE MANTER O CÓDIGO ORGANIZADO
- CODIGO EXPANSIVO
- SEPARATION OF CONCERNS (SEPARAÇÃO DE CONCEITOS)
- FACIL MANUTENÇÃO

DESVANTAGENS:

- COMPLEXIDADE ALTA
- QUANTIDADE DE CODIGO DIGITADO AUMENTA
- TENHA CUIDADOS COM: YAGBI, KISS (You aren't gonna need it, Keep it simple and stupid)

*/
